### ISSUE TITLE
API returns Javascript instead of JSON

### ISSUE THREAD

**Issue by davidbjames** [vedicscriptures/bhagavad-gita-api#17]
**API returns Javascript instead of JSON**
The random slok endpoint does not return JSON.

**To Reproduce**
1. Perform GET request with `https://bhagavadgitaapi.in/slok`
2. Receive Javascript

**Expected behavior**
JSON is returned with random slok

**Screenshots**
![Screen Shot 2022-06-20 at 9 41 15 AM](https://user-images.githubusercontent.com/870150/174550403-133d72c8-6a69-4b38-bb86-e1ce0da49f14.png)

**Comment by PtPrashantTripathi** [comment]
@davidbjames for random slok we are using a redirect method, and postman does not support JavaScript based redirects. That why you are getting the script code instead of JSON

**Solution :** nothing to worry about the same endpoint will work when you use this inside any code, like python or javascript

I am currently keeping this bug card open, please revert me back if there is any other issue with this solution

**Comment by davidbjames** [comment]
Ok. Thank you for your response. I am creating a small iOS app using a table view/collection view, so I'm not sure I can execute the Javascript in that context.

On a side note, if I have general questions about this API what/where is the best way to ask?

**Comment by PtPrashantTripathi** [comment]
I am singal handley managing this project. it will be deficult to answer each question but I'll try my best

Contact details:
vedic.scriptures@outlook.com
